//
// Created by development on 11.01.25.
//

#ifndef RECORD_RAW_HTTP_RECORD_RAW_HTTP_H
#define RECORD_RAW_HTTP_RECORD_RAW_HTTP_H

#define AUDIO_SAMPLE_RATE  (16000)
#define EXAMPLE_AUDIO_BITS         (16)
#define EXAMPLE_AUDIO_CHANNELS     (1)

#endif //RECORD_RAW_HTTP_RECORD_RAW_HTTP_H
